name: Python package

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-test.txt
    - name: Check with isort
      run: |
        pip install isort
        isort nettigo-air-monitor tests --check-only
    - name: Check with Black Code Formatter
      run: |
        pip install black
        black nettigo-air-monitor tests --check
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 nettigo-air-monitor tests
    - name: Lint with pylint
      run: |
        pip install pylint
        pylint nettigo-air-monitor tests
    - name: Test with mypy
      run: |
        mypy nettigo-air-monitor
    - name: Test with pytest
      run: |
        python setup.py test